// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_sit.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5IYRcDS-5zMBHMmh4iGoXQK_I2D3EBVs',
    appId: '1:254591535895:web:c4a954d1359330c2c40552',
    messagingSenderId: '254591535895',
    projectId: 'posternung',
    authDomain: 'posternung.firebaseapp.com',
    storageBucket: 'posternung.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRcWCtBFNUBGQ7pxw70VkUMS4suuBID-g',
    appId: '1:533903881255:android:b3c4d5a2a376ed7341ca02',
    messagingSenderId: '533903881255',
    projectId: 'posternung-sit',
    storageBucket: 'posternung-sit.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxtlqjLZmSigpxHMRf6T03FLk-isEU2F0',
    appId: '1:533903881255:ios:530e3bf51aa3565041ca02',
    messagingSenderId: '533903881255',
    projectId: 'posternung-sit',
    storageBucket: 'posternung-sit.firebasestorage.app',
    iosClientId:
        '533903881255-bra0e4fdu2l7kba1hknq105uli8rb3vc.apps.googleusercontent.com',
    iosBundleId: 'com.frameshine.posternung.sit',
  );
}
